services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    ports:
      - ${PORT}:9091
    volumes:
      - /persist/transmission:/config
      - ${DOWNLOADS}:/downloads
      - ${DOWNLOADS}/torrents:/watch
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    restart: unless-stopped

